baseURL = 'https://nikhil0307.github.io/nk-porto/'
languageCode = 'en-us'
title = "Nikhil's Portfolio"
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

  [[languages.en.menu.main]]
  name = "Home"
  url = "/"
  weight = 100

  [[languages.en.menu.main]]
  name = "Blog"
  url = "https://nikhilbaskar.substack.com/"
  weight = 200

  [[languages.en.menu.main]]
  name = "GitHub"
  url = "https://github.com/Nikhil0307"
  weight = 300

  [[languages.en.menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/nikhil0307/"
  weight = 400

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
defaultTheme = "auto"
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "Nikhil's Portfolio"
  imageUrl = "#"
  imageTitle = "My Image"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects"

    [[params.profileMode.buttons]]
    name = "Blog"
    url = "/blog"

  [params.homeInfoParams]
  Title = "Welcome to My Portfolio"
  Content = """
Hey there! I'm Nikhil, a backend engineer working on distributed systems, caching, and gRPC.  

Check out my projects and blog for deep dives into the tech I love!  

Want to connect? Reach out on [GitHub](https://github.com/Nikhil0307) or [LinkedIn](https://www.linkedin.com/in/nikhil0307/).
  """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Nikhil0307"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/nikhil0307/"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai"

[privacy.vimeo]
disabled = true
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = true
simple = true

[privacy.youtube]
disabled = true
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

